# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

demo = User.create!(email: 'demouser@demo.com', password: 'password', username: 'DEMO', dob: '19671017', gender: 'Female')
user1 = User.create!(email: 'user1@demo.com' , password: 'password' , username: 'user1' , dob: '20200411' , gender: 'Male')
user2 = User.create!(email: 'user2@demo.com' , password: 'password' , username: 'user2' , dob: '20200411' , gender: 'Male')
user3 = User.create!(email: 'user3@demo.com' , password: 'password' , username: 'user3' , dob: '20200411' , gender: 'Male')

podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user2.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user2.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user2.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user2.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user2.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user2.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user3.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user2.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user1.id)
podcast1 = Podcast.create!(podcast_name: 'test podcast' , user_id: user2.id)