# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'open-uri'
User.destroy_all

demo = User.create!(email: 'demouser@demo.com', password: 'password', username: 'DEMO', dob: '19671017', gender: 'Female')
user1 = User.create!(email: 'user1@demo.com' , password: 'password' , username: 'user1' , dob: '20200411' , gender: 'Male')
user2 = User.create!(email: 'user2@demo.com' , password: 'password' , username: 'user2' , dob: '20200411' , gender: 'Male')
user3 = User.create!(email: 'user3@demo.com' , password: 'password' , username: 'user3' , dob: '20200411' , gender: 'Male')

podcast1 = Podcast.create!(podcast_name: 'This American Life' , user_id: user1.id)
podcast2 = Podcast.create!(podcast_name: 'Serial' , user_id: user3.id)
podcast3 = Podcast.create!(podcast_name: 'Radiolab' , user_id: user2.id)
podcast4 = Podcast.create!(podcast_name: 'The Daily' , user_id: user2.id)
podcast5 = Podcast.create!(podcast_name: '99% Invisible' , user_id: user1.id)
podcast6 = Podcast.create!(podcast_name: 'Criminal' , user_id: user3.id)
podcast7 = Podcast.create!(podcast_name: 'How I Built This' , user_id: user3.id)
podcast8 = Podcast.create!(podcast_name: 'Stuff You Should Know' , user_id: user2.id)
podcast9 = Podcast.create!(podcast_name: 'WTF with Marc Maron' , user_id: user1.id)
podcast10 = Podcast.create!(podcast_name: 'Planet Money' , user_id: user3.id)
podcast11 = Podcast.create!(podcast_name: 'Slow Burn' , user_id: user2.id)
podcast12 = Podcast.create!(podcast_name: 'S-Town' , user_id: user1.id)
podcast13 = Podcast.create!(podcast_name: 'My Favorite Murder' , user_id: user3.id)
podcast14 = Podcast.create!(podcast_name: 'Pod Save America' , user_id: user1.id)
podcast15 = Podcast.create!(podcast_name: 'Invisibilia' , user_id: user1.id)
podcast16 = Podcast.create!(podcast_name: 'Dr. Death' , user_id: user1.id)
podcast17 = Podcast.create!(podcast_name: 'How Did This Get Made?' , user_id: user1.id)
podcast18 = Podcast.create!(podcast_name: 'Crimetown' , user_id: user2.id)
podcast19 = Podcast.create!(podcast_name: 'Welcome to Night Vale' , user_id: user3.id)
podcast20 = Podcast.create!(podcast_name: 'In the Dark' , user_id: user3.id)
podcast21 = Podcast.create!(podcast_name: 'Terrible, Thanks for Asking' , user_id: user3.id)
podcast22 = Podcast.create!(podcast_name: 'Revisionist History' , user_id: user3.id)
podcast23 = Podcast.create!(podcast_name: 'The Joe Rogan Experience' , user_id: user3.id)
podcast24 = Podcast.create!(podcast_name: 'Conan OBrien Needs a Friend' , user_id: user2.id)
podcast25 = Podcast.create!(podcast_name: 'H3 Podcast' , user_id: user3.id)
podcast26 = Podcast.create!(podcast_name: 'The Vergecast' , user_id: user2.id)
podcast27 = Podcast.create!(podcast_name: 'ESPN Daily' , user_id: user1.id)
podcast28 = Podcast.create!(podcast_name: 'You Are Not So Smart' , user_id: user1.id)
podcast29 = Podcast.create!(podcast_name: 'Fresh Air' , user_id: user1.id)
podcast30 = Podcast.create!(podcast_name: 'Song Exploder' , user_id: user2.id)

podcastart1 = open("https://podcaster-seeds.s3.amazonaws.com/thisamericanlife.png")
podcastart2 = open("https://podcaster-seeds.s3.amazonaws.com/serial.png")
podcastart3 = open("https://podcaster-seeds.s3.amazonaws.com/radiolab.jpg")
podcastart4 = open("https://podcaster-seeds.s3.amazonaws.com/thedaily.jpeg")
podcastart5 = open("https://podcaster-seeds.s3.amazonaws.com/99invisible.png")
podcastart6 = open("https://podcaster-seeds.s3.amazonaws.com/criminal.png")
podcastart7 = open("https://podcaster-seeds.s3.amazonaws.com/howibuiltthis.jpg")
podcastart8 = open("https://podcaster-seeds.s3.amazonaws.com/stuffyoushouldknow.jpg")
podcastart9 = open("https://podcaster-seeds.s3.amazonaws.com/wtf.jpg")
podcastart10 = open("https://podcaster-seeds.s3.amazonaws.com/planetmoney.jpg")
podcastart11= open("https://podcaster-seeds.s3.amazonaws.com/slowburn.jpeg")
podcastart12 = open("https://podcaster-seeds.s3.amazonaws.com/stown.jpg")
podcastart13 = open("https://podcaster-seeds.s3.amazonaws.com/myfavoritemurder.jpg")
podcastart14 = open("https://podcaster-seeds.s3.amazonaws.com/podsaveamerica.jpeg")
podcastart15 = open("https://podcaster-seeds.s3.amazonaws.com/invisibilia.jpg")
podcastart16 = open("https://podcaster-seeds.s3.amazonaws.com/drdeath.jpeg")
podcastart17 = open("https://podcaster-seeds.s3.amazonaws.com/howdidthisgetmade.jpg")
podcastart18 = open("https://podcaster-seeds.s3.amazonaws.com/crimetown.png")
podcastart19 = open("https://podcaster-seeds.s3.amazonaws.com/welcometonightvale.jpg")
podcastart20 = open("https://podcaster-seeds.s3.amazonaws.com/inthedark.jpg")
podcastart21 = open("https://podcaster-seeds.s3.amazonaws.com/terriblethanksforasking.png")
podcastart22 = open("https://podcaster-seeds.s3.amazonaws.com/revisionisthistory.jpeg")
podcastart23 = open("https://podcaster-seeds.s3.amazonaws.com/joerogan.jpeg")
podcastart24 = open("https://podcaster-seeds.s3.amazonaws.com/conanneedsafriend.jpg")
podcastart25 = open("https://podcaster-seeds.s3.amazonaws.com/theh3podcast.jpg")
podcastart26 = open("https://podcaster-seeds.s3.amazonaws.com/thevergecast.png")
podcastart27 = open("https://podcaster-seeds.s3.amazonaws.com/espndailypodcast.jpg")
podcastart28 = open("https://podcaster-seeds.s3.amazonaws.com/youarenotsosmart.jpg")
podcastart29 = open("https://podcaster-seeds.s3.amazonaws.com/freshair.jpg")
podcastart30 = open("https://podcaster-seeds.s3.amazonaws.com/songexploder.png")

podcast1.podcast_art.attach({io: podcastart1, filename: "thisamericanlife.png"})
podcast2.podcast_art.attach({io: podcastart2, filename: "serial.png"})
podcast3.podcast_art.attach({io: podcastart3, filename: "radiolab.jpg"})
podcast4.podcast_art.attach({io: podcastart4, filename: "thedaily.jpeg"})
podcast5.podcast_art.attach({io: podcastart5, filename: "99invisible.png"})
podcast6.podcast_art.attach({io: podcastart6, filename: "criminal.png"})
podcast7.podcast_art.attach({io: podcastart7, filename: "howibuiltthis.jpg"})
podcast8.podcast_art.attach({io: podcastart8, filename: "stuffyoushouldknow.jpg"})
podcast9.podcast_art.attach({io: podcastart9, filename: "wtf.jpg"})
podcast10.podcast_art.attach({io: podcastart10, filename: "planetmoney.jpg"})
podcast11.podcast_art.attach({io: podcastart11, filename: "slowburn.jpeg"})
podcast12.podcast_art.attach({io: podcastart12, filename: "stown.jpg"})
podcast13.podcast_art.attach({io: podcastart13, filename: "myfavoritemurder.jpg"})
podcast14.podcast_art.attach({io: podcastart14, filename: "podsaveamerica.jpeg"})
podcast15.podcast_art.attach({io: podcastart15, filename: "invisibilia.jpg"})
podcast16.podcast_art.attach({io: podcastart16, filename: "drdeath.jpeg"})
podcast17.podcast_art.attach({io: podcastart17, filename: "howdidthisgetmade.jpg"})
podcast18.podcast_art.attach({io: podcastart18, filename: "crimetown.png"})
podcast19.podcast_art.attach({io: podcastart19, filename: "welcometonightvale.jpg"})
podcast20.podcast_art.attach({io: podcastart20, filename: "inthedark.jpg"})
podcast21.podcast_art.attach({io: podcastart21, filename: "terriblethanksforasking.png"})
podcast22.podcast_art.attach({io: podcastart22, filename: "revisionisthistory.jpeg"})
podcast23.podcast_art.attach({io: podcastart23, filename: "joerogan.jpeg"})
podcast24.podcast_art.attach({io: podcastart24, filename: "conanneedsafriend.jpg"})
podcast25.podcast_art.attach({io: podcastart25, filename: "theh3podcast.jpg"})
podcast26.podcast_art.attach({io: podcastart26, filename: "thevergecast.png"})
podcast27.podcast_art.attach({io: podcastart27, filename: "espndailypodcast.jpg"})
podcast28.podcast_art.attach({io: podcastart28, filename: "youarenotsosmart.jpg"})
podcast29.podcast_art.attach({io: podcastart29, filename: "freshair.jpg"})
podcast30.podcast_art.attach({io: podcastart30, filename: "songexploder.png"})