# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'open-uri'
User.destroy_all

demo = User.create!(email: 'demouser@demo.com', password: 'password', username: 'DEMO', dob: '19671017', gender: 'Female')
user1 = User.create!(email: 'user1@demo.com' , password: 'password' , username: 'Ira Glass' , dob: '20200411' , gender: 'Male')
user2 = User.create!(email: 'user2@demo.com' , password: 'password' , username: 'Sarah Koenig' , dob: '20200411' , gender: 'Male')
user3 = User.create!(email: 'user3@demo.com' , password: 'password' , username: 'Jad Abumrad & Robert Krulwich' , dob: '20200411' , gender: 'Male')
user4 = User.create!(email: 'user4@demo.com' , password: 'password' , username: 'Michael Barbaro' , dob: '20200411' , gender: 'Male')
user5 = User.create!(email: 'user5@demo.com' , password: 'password' , username: 'Roman Mars' , dob: '20200411' , gender: 'Male')
user6 = User.create!(email: 'user6@demo.com' , password: 'password' , username: 'Phoebe Judge' , dob: '20200411' , gender: 'Male')
user7 = User.create!(email: 'user7@demo.com' , password: 'password' , username: 'Guy Raz' , dob: '20200411' , gender: 'Male')
user8 = User.create!(email: 'user8@demo.com' , password: 'password' , username: 'Josh Clark & Charles W. "Chuck" Bryant' , dob: '20200411' , gender: 'Male')
user9 = User.create!(email: 'user9@demo.com' , password: 'password' , username: 'Marc Maron' , dob: '20200411' , gender: 'Male')
user10 = User.create!(email: 'user10@demo.com' , password: 'password' , username: 'NPR' , dob: '20200411' , gender: 'Male')
user11 = User.create!(email: 'user11@demo.com' , password: 'password' , username: 'Leon Neyfakh' , dob: '20200411' , gender: 'Male')
user12 = User.create!(email: 'user12@demo.com' , password: 'password' , username: 'Brian Reed' , dob: '20200411' , gender: 'Male')
user13 = User.create!(email: 'user13@demo.com' , password: 'password' , username: 'Georgia Hardstark & Karen Kilgariff', dob: '20200411' , gender: 'Male')
user14 = User.create!(email: 'user14@demo.com' , password: 'password' , username: 'Jon Favreau & Daniel Pfeiffer & Jon Lovett & Tommy Vietor', dob: '20200411' , gender: 'Male')
user15 = User.create!(email: 'user15@demo.com' , password: 'password' , username: 'Alix Spiegel & Hanna Rosin & Lulu Miller', dob: '20200411' , gender: 'Male')
user16 = User.create!(email: 'user16@demo.com' , password: 'password' , username: 'Laura Beil', dob: '20200411' , gender: 'Male')
user17 = User.create!(email: 'user17@demo.com' , password: 'password' , username: 'Paul Scheer & June Diane Raphael & Jason Mantzoukas' , dob: '20200411' , gender: 'Male')
user18 = User.create!(email: 'user18@demo.com' , password: 'password' , username: 'Marc Smerling & Zac Stuart-Pontier' , dob: '20200411' , gender: 'Male')
user19 = User.create!(email: 'user19@demo.com' , password: 'password' , username: 'Joseph Fink & Jeffrey Cranor' , dob: '20200411' , gender: 'Male')
user20 = User.create!(email: 'user20@demo.com' , password: 'password' , username: 'Madeleine Baran' , dob: '20200411' , gender: 'Male')
user21 = User.create!(email: 'user21@demo.com' , password: 'password' , username: 'Nora McInerny' , dob: '20200411' , gender: 'Male')
user22 = User.create!(email: 'user22@demo.com' , password: 'password' , username: 'Malcolm Gladwell' , dob: '20200411' , gender: 'Male')
user23 = User.create!(email: 'user23@demo.com' , password: 'password' , username: 'Joe Rogan' , dob: '20200411' , gender: 'Male')
user24 = User.create!(email: 'user24@demo.com' , password: 'password' , username: 'Conan OBrien' , dob: '20200411' , gender: 'Male')
user25 = User.create!(email: 'user25@demo.com' , password: 'password' , username: 'Ethan & Hila Klein' , dob: '20200411' , gender: 'Male')
user26 = User.create!(email: 'user26@demo.com' , password: 'password' , username: 'Nilay Patel and Dieter Bohn' , dob: '20200411' , gender: 'Male')
user27 = User.create!(email: 'user27@demo.com' , password: 'password' , username: 'Mina Kimes' , dob: '20200411' , gender: 'Male')
user28 = User.create!(email: 'user28@demo.com' , password: 'password' , username: 'David McRaney' , dob: '20200411' , gender: 'Male')
user29 = User.create!(email: 'user29@demo.com' , password: 'password' , username: 'Terry Gross' , dob: '20200411' , gender: 'Male')
user30 = User.create!(email: 'user30@demo.com' , password: 'password' , username: 'Hrishikesh Hirway' , dob: '20200411' , gender: 'Male')

podcast1 = Podcast.create!(podcast_name: 'This American Life' , user_id: user1.id)
podcast2 = Podcast.create!(podcast_name: 'Serial' , user_id: user2.id)
podcast3 = Podcast.create!(podcast_name: 'Radiolab' , user_id: user3.id)
podcast4 = Podcast.create!(podcast_name: 'The Daily' , user_id: user4.id)
podcast5 = Podcast.create!(podcast_name: '99% Invisible' , user_id: user5.id)
podcast6 = Podcast.create!(podcast_name: 'Criminal' , user_id: user6.id)
podcast7 = Podcast.create!(podcast_name: 'How I Built This' , user_id: user7.id)
podcast8 = Podcast.create!(podcast_name: 'Stuff You Should Know' , user_id: user8.id)
podcast9 = Podcast.create!(podcast_name: 'WTF with Marc Maron' , user_id: user9.id)
podcast10 = Podcast.create!(podcast_name: 'Planet Money' , user_id: user10.id)
podcast11 = Podcast.create!(podcast_name: 'Slow Burn' , user_id: user11.id)
podcast12 = Podcast.create!(podcast_name: 'S-Town' , user_id: user12.id)
podcast13 = Podcast.create!(podcast_name: 'My Favorite Murder' , user_id: user13.id)
podcast14 = Podcast.create!(podcast_name: 'Pod Save America' , user_id: user14.id)
podcast15 = Podcast.create!(podcast_name: 'Invisibilia' , user_id: user15.id)
podcast16 = Podcast.create!(podcast_name: 'Dr. Death' , user_id: user16.id)
podcast17 = Podcast.create!(podcast_name: 'How Did This Get Made?' , user_id: user17.id)
podcast18 = Podcast.create!(podcast_name: 'Crimetown' , user_id: user18.id)
podcast19 = Podcast.create!(podcast_name: 'Welcome to Night Vale' , user_id: user19.id)
podcast20 = Podcast.create!(podcast_name: 'In the Dark' , user_id: user20.id)
podcast21 = Podcast.create!(podcast_name: 'Terrible, Thanks for Asking' , user_id: user21.id)
podcast22 = Podcast.create!(podcast_name: 'Revisionist History' , user_id: user22.id)
podcast23 = Podcast.create!(podcast_name: 'The Joe Rogan Experience' , user_id: user23.id)
podcast24 = Podcast.create!(podcast_name: 'Conan OBrien Needs a Friend' , user_id: user24.id)
podcast25 = Podcast.create!(podcast_name: 'H3 Podcast' , user_id: user25.id)
podcast26 = Podcast.create!(podcast_name: 'The Vergecast' , user_id: user26.id)
podcast27 = Podcast.create!(podcast_name: 'ESPN Daily' , user_id: user27.id)
podcast28 = Podcast.create!(podcast_name: 'You Are Not So Smart' , user_id: user28.id)
podcast29 = Podcast.create!(podcast_name: 'Fresh Air' , user_id: user29.id)
podcast30 = Podcast.create!(podcast_name: 'Song Exploder' , user_id: user30.id)

episode1 = Episode.create!(episode_name: 'Low Hum of Menace', podcast_id: podcast1.id )
episode2 = Episode.create!(episode_name: 'Fiasco!', podcast_id: podcast1.id )

episode3 = Episode.create!(episode_name: 'The Snowball Effect', podcast_id: podcast2.id )
episode4 = Episode.create!(episode_name: 'You in the Red Shirt', podcast_id: podcast2.id )

episode5 = Episode.create!(episode_name: 'Numbers', podcast_id: podcast3.id )
episode6 = Episode.create!(episode_name: 'Six Feet', podcast_id: podcast3.id )

episode7 = Episode.create!(episode_name: 'Kicked Out of China', podcast_id: podcast4.id )
episode8 = Episode.create!(episode_name: 'Examining the Allegation Against Joe Biden', podcast_id: podcast4.id )

episode9 = Episode.create!(episode_name: 'Unsheltered in Place', podcast_id: podcast5.id )
episode10 = Episode.create!(episode_name: 'Wipe Out', podcast_id: podcast5.id )

episode11 = Episode.create!(episode_name: '527 Lime Street', podcast_id: podcast6.id )
episode12 = Episode.create!(episode_name: 'Call Russ Ewing', podcast_id: podcast6.id )

episode13 = Episode.create!(episode_name: 'Swell: Sarah Kauss', podcast_id: podcast7.id )
episode14 = Episode.create!(episode_name: 'Live with Guy Online: Jeni Britton Bauer', podcast_id: podcast7.id )

episode15 = Episode.create!(episode_name: 'How Wastewater Treatment Works', podcast_id: podcast8.id )
episode16 = Episode.create!(episode_name: 'Bidets: Now More Than Ever', podcast_id: podcast8.id )

episode17 = Episode.create!(episode_name: 'Sam Morril', podcast_id: podcast9.id )
episode18 = Episode.create!(episode_name: 'Taylor Tomlinson', podcast_id: podcast9.id )

episode19 = Episode.create!(episode_name: 'The Big Small Business Rescue', podcast_id: podcast10.id )
episode20 = Episode.create!(episode_name: 'What if No One Pays Rent?', podcast_id: podcast10.id )

episode21 = Episode.create!(episode_name: 'To Live and Die in LA', podcast_id: podcast11.id )
episode22 = Episode.create!(episode_name: 'Dead Wrong', podcast_id: podcast11.id )

episode23 = Episode.create!(episode_name: 'The Big Apple', podcast_id: podcast12.id )
episode24 = Episode.create!(episode_name: 'Stolen Valor', podcast_id: podcast12.id )

episode25 = Episode.create!(episode_name: 'Good Shabbos', podcast_id: podcast13.id )
episode26 = Episode.create!(episode_name: 'Robe Convention', podcast_id: podcast13.id )

episode27 = Episode.create!(episode_name: 'Trumps Grand Opening', podcast_id: podcast14.id )
episode28 = Episode.create!(episode_name: 'Biden v. Trump v. Coronavirus', podcast_id: podcast14.id )

episode29 = Episode.create!(episode_name: 'The Reluctant Immortalist', podcast_id: podcast15.id )
episode30 = Episode.create!(episode_name: 'White v. White?', podcast_id: podcast15.id )

episode31 = Episode.create!(episode_name: 'Introducing The Dating Game Killer', podcast_id: podcast16.id )
episode32 = Episode.create!(episode_name: 'Introducing Even the Rich', podcast_id: podcast16.id )

episode33 = Episode.create!(episode_name: 'Prequel to Episode 235', podcast_id: podcast17.id )
episode34 = Episode.create!(episode_name: 'Prequel to Episode 236', podcast_id: podcast17.id )

episode35 = Episode.create!(episode_name: 'Operation Backbone', podcast_id: podcast18.id )
episode36 = Episode.create!(episode_name: 'Introducing Mogul', podcast_id: podcast18.id )

episode37 = Episode.create!(episode_name: 'Delta', podcast_id: podcast19.id )
episode38 = Episode.create!(episode_name: 'Charlie', podcast_id: podcast19.id )

episode39 = Episode.create!(episode_name: 'The Recusal', podcast_id: podcast20.id )
episode40 = Episode.create!(episode_name: 'Home', podcast_id: podcast20.id )

episode41 = Episode.create!(episode_name: 'Welcome To The Club', podcast_id: podcast21.id )
episode42 = Episode.create!(episode_name: 'Emily and Chanel', podcast_id: podcast21.id )

episode43 = Episode.create!(episode_name: 'Go and See', podcast_id: podcast22.id )
episode44 = Episode.create!(episode_name: 'Deep Background with Noah Feldman', podcast_id: podcast22.id )

episode45 = Episode.create!(episode_name: 'Chris Delia', podcast_id: podcast23.id )
episode46 = Episode.create!(episode_name: 'Tim Dillon', podcast_id: podcast23.id )

episode47 = Episode.create!(episode_name: 'Steve Coogan', podcast_id: podcast24.id )
episode48 = Episode.create!(episode_name: 'Whitney Cummings', podcast_id: podcast24.id )

episode49 = Episode.create!(episode_name: 'We Speak with An Epidemiologist About Coronavirus', podcast_id: podcast25.id )
episode50 = Episode.create!(episode_name: 'Is iDubbbz A Simp?', podcast_id: podcast25.id )

episode51 = Episode.create!(episode_name: 'Microsoft CTO Kevin Scott on AI for rural America', podcast_id: podcast26.id )
episode52 = Episode.create!(episode_name: 'Zooms privacy concerns, Apple buys Dark Sky, and Sprint is dead', podcast_id: podcast26.id )

episode53 = Episode.create!(episode_name: 'The Day Baseball Stood Still for Clayton Kershaw', podcast_id: podcast27.id )
episode54 = Episode.create!(episode_name: 'Gambling on Sports When Sports Are Shut Down', podcast_id: podcast27.id )

episode55 = Episode.create!(episode_name: 'Socks and Crocs', podcast_id: podcast28.id )
episode56 = Episode.create!(episode_name: 'Bad Advice', podcast_id: podcast28.id )

episode57 = Episode.create!(episode_name: 'The Big Business Of Inequality', podcast_id: podcast29.id )
episode58 = Episode.create!(episode_name: 'The FBI, CIA & The Truth About Americas Deep State', podcast_id: podcast29.id )

episode59 = Episode.create!(episode_name: 'FKA twigs - Mirrored Heart', podcast_id: podcast30.id )
episode60 = Episode.create!(episode_name: 'Nathaniel Rateliff - And Its Still Alright', podcast_id: podcast30.id )


podcastart1 = open("https://podcaster-seeds.s3.amazonaws.com/thisamericanlife.png")
podcastart2 = open("https://podcaster-seeds.s3.amazonaws.com/serial.png")
podcastart3 = open("https://podcaster-seeds.s3.amazonaws.com/radiolab.jpg")
podcastart4 = open("https://podcaster-seeds.s3.amazonaws.com/thedaily.jpeg")
podcastart5 = open("https://podcaster-seeds.s3.amazonaws.com/99invisible.png")
podcastart6 = open("https://podcaster-seeds.s3.amazonaws.com/criminal.png")
podcastart7 = open("https://podcaster-seeds.s3.amazonaws.com/howibuiltthis.jpg")
podcastart8 = open("https://podcaster-seeds.s3.amazonaws.com/stuffyoushouldknow.jpg")
podcastart9 = open("https://podcaster-seeds.s3.amazonaws.com/wtf.jpg")
podcastart10 = open("https://podcaster-seeds.s3.amazonaws.com/planetmoney.jpg")
podcastart11= open("https://podcaster-seeds.s3.amazonaws.com/slowburn.jpeg")
podcastart12 = open("https://podcaster-seeds.s3.amazonaws.com/stown.jpg")
podcastart13 = open("https://podcaster-seeds.s3.amazonaws.com/myfavoritemurder.jpg")
podcastart14 = open("https://podcaster-seeds.s3.amazonaws.com/podsaveamerica.jpeg")
podcastart15 = open("https://podcaster-seeds.s3.amazonaws.com/invisibilia.jpg")
podcastart16 = open("https://podcaster-seeds.s3.amazonaws.com/drdeath.jpeg")
podcastart17 = open("https://podcaster-seeds.s3.amazonaws.com/howdidthisgetmade.jpg")
podcastart18 = open("https://podcaster-seeds.s3.amazonaws.com/crimetown.png")
podcastart19 = open("https://podcaster-seeds.s3.amazonaws.com/welcometonightvale.jpg")
podcastart20 = open("https://podcaster-seeds.s3.amazonaws.com/inthedark.jpg")
podcastart21 = open("https://podcaster-seeds.s3.amazonaws.com/terriblethanksforasking.png")
podcastart22 = open("https://podcaster-seeds.s3.amazonaws.com/revisionisthistory.jpeg")
podcastart23 = open("https://podcaster-seeds.s3.amazonaws.com/joerogan.jpeg")
podcastart24 = open("https://podcaster-seeds.s3.amazonaws.com/conanneedsafriend.jpg")
podcastart25 = open("https://podcaster-seeds.s3.amazonaws.com/theh3podcast.jpg")
podcastart26 = open("https://podcaster-seeds.s3.amazonaws.com/thevergecast.png")
podcastart27 = open("https://podcaster-seeds.s3.amazonaws.com/espndailypodcast.jpg")
podcastart28 = open("https://podcaster-seeds.s3.amazonaws.com/youarenotsosmart.jpg")
podcastart29 = open("https://podcaster-seeds.s3.amazonaws.com/freshair.jpg")
podcastart30 = open("https://podcaster-seeds.s3.amazonaws.com/songexploder.png")

podcast1.podcast_art.attach({io: podcastart1, filename: "thisamericanlife.png"})
podcast2.podcast_art.attach({io: podcastart2, filename: "serial.png"})
podcast3.podcast_art.attach({io: podcastart3, filename: "radiolab.jpg"})
podcast4.podcast_art.attach({io: podcastart4, filename: "thedaily.jpeg"})
podcast5.podcast_art.attach({io: podcastart5, filename: "99invisible.png"})
podcast6.podcast_art.attach({io: podcastart6, filename: "criminal.png"})
podcast7.podcast_art.attach({io: podcastart7, filename: "howibuiltthis.jpg"})
podcast8.podcast_art.attach({io: podcastart8, filename: "stuffyoushouldknow.jpg"})
podcast9.podcast_art.attach({io: podcastart9, filename: "wtf.jpg"})
podcast10.podcast_art.attach({io: podcastart10, filename: "planetmoney.jpg"})
podcast11.podcast_art.attach({io: podcastart11, filename: "slowburn.jpeg"})
podcast12.podcast_art.attach({io: podcastart12, filename: "stown.jpg"})
podcast13.podcast_art.attach({io: podcastart13, filename: "myfavoritemurder.jpg"})
podcast14.podcast_art.attach({io: podcastart14, filename: "podsaveamerica.jpeg"})
podcast15.podcast_art.attach({io: podcastart15, filename: "invisibilia.jpg"})
podcast16.podcast_art.attach({io: podcastart16, filename: "drdeath.jpeg"})
podcast17.podcast_art.attach({io: podcastart17, filename: "howdidthisgetmade.jpg"})
podcast18.podcast_art.attach({io: podcastart18, filename: "crimetown.png"})
podcast19.podcast_art.attach({io: podcastart19, filename: "welcometonightvale.jpg"})
podcast20.podcast_art.attach({io: podcastart20, filename: "inthedark.jpg"})
podcast21.podcast_art.attach({io: podcastart21, filename: "terriblethanksforasking.png"})
podcast22.podcast_art.attach({io: podcastart22, filename: "revisionisthistory.jpeg"})
podcast23.podcast_art.attach({io: podcastart23, filename: "joerogan.jpeg"})
podcast24.podcast_art.attach({io: podcastart24, filename: "conanneedsafriend.jpg"})
podcast25.podcast_art.attach({io: podcastart25, filename: "theh3podcast.jpg"})
podcast26.podcast_art.attach({io: podcastart26, filename: "thevergecast.png"})
podcast27.podcast_art.attach({io: podcastart27, filename: "espndailypodcast.jpg"})
podcast28.podcast_art.attach({io: podcastart28, filename: "youarenotsosmart.jpg"})
podcast29.podcast_art.attach({io: podcastart29, filename: "freshair.jpg"})
podcast30.podcast_art.attach({io: podcastart30, filename: "songexploder.png"})
